version: "3.9"

services:
  recipes_db:
    container_name: recipes_db
    image: postgres:14.3-alpine
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${RECIPES_DB_PASSWORD}
      POSTGRES_USER: ${RECIPES_DB_USER}
      POSTGRES_DB: ${RECIPES_DB_DB}
    ports:
      - ${RECIPES_DB_PORT_HOST}:${RECIPES_DB_PORT_CONTAINER}
    volumes:
      - recipes_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - network

  recipe-service:
    container_name: recipe-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${FASTAPI_EXPOSE_PORT}:${FASTAPI_PORT}
    restart: unless-stopped
    networks:
      - network

volumes:
  recipes_db_data:

networks:
  network:
    name: app_network
    driver: external