version: "3.9"

services:
  recipes_db:
    container_name: recipes_db
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: ${RECIPES_DB_PASSWORD}
      POSTGRES_USER: ${RECIPES_DB_USER}
      POSTGRES_DB: ${RECIPES_DB_DB}
    ports:
      - ${RECIPES_DB_PORT}:5432
    volumes:
      - recipes_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - api

volumes:
  recipes_db_data:

networks:
  api:
    driver: bridge